name: tweenengine
author: Xavier Guzman
version: 0.9.0
description: "A port of the java Universal tween engine created by Aurelien Ribbon.\r\
  \n\r\nThis library helps you to animate any attribute for any object"
environment:
  sdk: 1.1.1
dependencies:
  browser: any
